service: khmercut
frameworkVersion: '4'

provider:
  name: aws
  region: ap-southeast-1
  architecture: arm64
  versionFunctions: false
  runtime: provided.al2

layers:
  khmercut:
    path: layer
    name: khmercut
    description: khmercut for AWS Lambda
    compatibleArchitectures:
      - arm64
    licenseInfo: GPLv3
    retain: false

package:
  individually: true
